excluded:
  - ${PWD}/Carthage
  - ${PWD}/Pods
  - ${PWD}/DerivedData

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

cyclomatic_complexity:
  ignores_case_statements: true
